version: '3.8'
services:
  proxy:
    image: adrianfish/dialang-proxy
    depends_on:
      web:
        condition: service_started
      content:
        condition: service_started
    ports:
      - "80:80"
    restart: unless-stopped
  content:
    image: adrianfish/dialang-content
    restart: unless-stopped
  web:
    image: adrianfish/dialang-web
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
  db:
    image: adrianfish/dialang-db
    environment:
      POSTGRES_USER: dialangadmin
      POSTGRES_PASSWORD: e785598fffccc098afda8eb6e42494e5
      POSTGRES_DB: dialang
      POSTGRES_HOST_AUTH_METHOD: md5
    restart: unless-stopped
